version: '3.5'

services:
  go-bootcamp:
    container_name: go-bootcamp
    image: liyaodev/go-bootcamp-env:v1.0.0
    # # 本地构建
    # build:
    #   context: .
    #   dockerfile: build/docker/build_env/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - .:/go/src/github.com/codetodo-io/go-bootcamp:delegated
      - ${GO_BOOTCAMP_ROOT_DIR:-.}/volumes/vscode-extensions:/root/.vscode-server:delegated
    working_dir: /go/src/github.com/codetodo-io/go-bootcamp

networks:
  default:
    name: go_bootcamp_dev
